#!/usr/bin/env node
// Bundle a real administrator report into the page.
//
// The venue's CSP is default-src 'none' with script-src 'self', so the surface
// cannot fetch its own data — it has to arrive as a script. That constraint is
// worth keeping: the page ships with a report that was actually produced, not a
// mock, and the build fails rather than shipping a stale one.
//
//   node scripts/build-mfile.mjs
//   node scripts/build-mfile.mjs --check   # fails if the bundle is out of date

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { administer } from "../src/administer.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "public", "mfile", "data.js");

// The bundle is built from a checked-in fixture, not from a --self run.
//
// --self was the first version and it was wrong twice over. It made the page a
// function of every file in the repository, so `--check` failed on any commit
// that touched anything; and it showed a reader this repository's own .mjs and
// .json files, when what they want to see is what a report on a drive of audio,
// video and photos looks like. The fixture is labelled as invented and it
// exercises every case the four questions have to handle.
const fixture = JSON.parse(fs.readFileSync(path.join(ROOT, "mfile", "fixture.json"), "utf8"));
const report = administer(fixture.manifest);

// The per-file verdicts are not shipped. The surface reads the shape of a
// store, and 152 rows of this repository's own paths is not that.
const { verdicts, scanned_at, ...shape } = report;

const criteria = JSON.parse(fs.readFileSync(path.join(ROOT, "mfile", "criteria.json"), "utf8"));
const intake = JSON.parse(fs.readFileSync(path.join(ROOT, "mfile", "questions", "intake.json"), "utf8"));
const stores = JSON.parse(fs.readFileSync(path.join(ROOT, "mfile", "stores.json"), "utf8"));
const doors = JSON.parse(fs.readFileSync(path.join(ROOT, "mfile", "doors.json"), "utf8"));

const bundle = {
  // Deliberately not scanned_at: a timestamp would make every build a diff.
  demonstrated_on: "an invented eighteen-file phone folder — see mfile/fixture.json",
  demonstrates: fixture.what_it_demonstrates,
  shape,
  questions: criteria.questions.map((q) => ({
    key: q.key,
    asks: q.asks,
    rule: q.rule,
    requires: q.requires,
    withholds: q.degraded.must_not_say,
    also_withholds: q.degraded.must_not_say_either ?? null,
    instead: q.degraded.says,
    because: q.degraded.reason ?? null,
  })),
  intake: intake.questions.map((q) => ({ ask: q.ask, why: q.why, unblocks: q.unblocks })),
  refuses: intake.refuses,
  stores: stores.stores.map((s) => ({
    name: s.name,
    access: s.access,
    reachable: s.reachable_from_repository,
    owed: s.owed ?? null,
  })),
  doors: doors.doors.map((d) => ({
    name: d.name,
    identity: d.identity,
    reads: d.reads,
    cannot_read: d.cannot_read,
  })),
  hard_rules: doors.rules.filter((r) => r.severity === "hard").map((r) => ({ rule: r.rule, why: r.why })),
  people: doors.people.note,
  load_bearing: criteria.load_bearing,
};

const body = `// Generated by scripts/build-mfile.mjs — do not edit.\nwindow.MFILE = ${JSON.stringify(bundle, null, 2)};\n`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current !== body) {
    console.error("build-mfile: public/mfile/data.js is out of date. Run `npm run build:mfile`.");
    process.exit(1);
  }
  console.log("PASS  mfile bundle in sync");
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);
  console.log(`build-mfile: ${shape.records} records, ${bundle.questions.length} questions -> public/mfile/data.js`);
}
